# application project makefile

SHELL          = /bin/bash
CFG           ?= .env
PRG           ?= $(shell basename $$PWD)

# -----------------------------------------------------------------------------
# Runtime data

APP_PORT      ?= 7070

PGHOST        ?= localhost
PGPORT        ?= 5432
PGDATABASE    ?= $(PRG)
PGUSER        ?= $(PRG)
PGPASSWORD    ?= $(shell < /dev/urandom tr -dc A-Za-z0-9 | head -c14; echo)
PGAPPNAME     ?= $(PRG)

# -----------------------------------------------------------------------------
# docker part

APP_IMAGE  ?= $(PRG)

# image prefix
PROJECT_NAME ?= $(PRG)

# docker-compose image
DC_VER ?= 1.23.2

# -----------------------------------------------------------------------------
# dcape part

# dcape containers name prefix
DCAPE_PROJECT_NAME ?= dcape
# dcape postgresql container name
DCAPE_DB           ?= $(DCAPE_PROJECT_NAME)_db_1


define CONFIG_DEFAULT
# ------------------------------------------------------------------------------
# application config file, generated by make $(CFG)

# App/Docker listen addr
APP_PORT=$(APP_PORT)

# Docker image tag
APP_IMAGE=$(APP_IMAGE)

# Database

# Host
PGHOST=$(PGHOST)
# Port
PGPORT=$(PGPORT)
# Name
PGDATABASE=$(PGDATABASE)
# User
PGUSER=$(PGUSER)
# Password
PGPASSWORD=$(PGPASSWORD)
# App name
PGAPPNAME=$(PGAPPNAME)

endef
export CONFIG_DEFAULT

# ------------------------------------------------------------------------------

-include $(CFG)
export

.PHONY: all api dep build run lint test up up-db down psql clean help

all: help

api: ## Generate grpc go sources
	go generate ./...

dep: ## Get the dependencies
	@go get -v -d ./...

build: dep ## Build the binary file for server
	@go build -i -v .

run: ## Build and run binary
	@go run . --debug --db.addr=localhost:5432 --addr=localhost:${APP_PORT} \
	--db.name=${PGDATABASE} --db.user=${PGUSER} --db.password=${PGPASSWORD}

lint: ## Run linter
	@golangci-lint run ./...

test: ## Run grpc client tests
	APP_ADDR=localhost:${APP_PORT} \
	go test -v -count=1 .

# ------------------------------------------------------------------------------
# Docker

up: ## Start pg and app containers
up: CMD=up -d
up: dc

up-db: ## Start pg container only
up-db: CMD=up -d db
up-db: dc

down: ## Stop containers and remove them
down: CMD=rm -f -s
down: dc

# $$PWD используется для того, чтобы текущий каталог был доступен 
# в контейнере docker-compose по тому же пути
# и относительные тома новых контейнеров могли его использовать
dc: docker-compose.yml ## Run docker-compose (make dc CMD=build)
	@docker run --rm  \
	  -v /var/run/docker.sock:/var/run/docker.sock \
	  -v $$PWD:$$PWD \
	  -w $$PWD \
	  docker/compose:$(DC_VER) \
	  -p $$PROJECT_NAME \
	  $(CMD)

# ------------------------------------------------------------------------------
# DB operations with docker and [dcape](https://github.com/dopos/dcape)

# (internal) Wait for postgresql container start
docker-wait:
	@echo -n "Checking PG is ready..."
	@until [[ `docker inspect -f "{{.State.Health.Status}}" $$DCAPE_DB` == healthy ]] ; do sleep 1 ; echo -n "." ; done
	@echo "Ok"

dcape-db-create: docker-wait ## Create user, db and load dump
	@echo "*** $@ ***" ; \
	docker exec -i $$DCAPE_DB psql -U postgres -c "CREATE USER \"$$PGUSER\" WITH PASSWORD '$$PGPASSWORD';" || true ; \
	docker exec -i $$DCAPE_DB psql -U postgres -c "CREATE DATABASE \"$$PGDATABASE\" OWNER \"$$PGUSER\";" || db_exists=1 ; \
	if [[ ! "$$db_exists" ]] ; then \
	    cat sql/crebas.sql | docker exec -i $$DCAPE_DB psql -U postgres -d $$PGDATABASE -1 -X ; \
	    echo "Restore completed" ; \
	fi

dcape-db-drop: docker-wait ## Drop database and user
	@echo "*** $@ ***"
	@docker exec -it $$DCAPE_DB psql -U postgres -c "DROP DATABASE \"$$PGDATABASE\";" || true
	@docker exec -it $$DCAPE_DB psql -U postgres -c "DROP USER \"$$PGUSER\";" || true

dcape-psql: docker-wait ## Run psql
	@docker exec -it $$DCAPE_DB psql -U $$PGUSER -d $$PGDATABASE

dcape-start: dcape-db-create up

dcape-start-hook: dcape-db-create reup

dcape-stop: down

# ------------------------------------------------------------------------------

psql: ## Run psql via postgresql docker container
	@docker exec -it $${PROJECT_NAME}_db_1 psql -U $$PGUSER -d $$PGDATABASE

$(CFG):
	@[ -f $@ ] || { echo "$$CONFIG_DEFAULT" > $@ ; echo "Warning: Created default $@" ; }

conf: ## Create initial config
	@true

clean: ## Remove previous builds
	@rm -f $(PRG)

help: ## Display this help screen
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' Makefile | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
