# application project makefile

SHELL          = /bin/bash
CFG           ?= .env
PRG           ?= $(shell basename $$PWD)

# -----------------------------------------------------------------------------
# Runtime data

APP_LISTEN    ?= 7070

PGHOST        ?= localhost
PGPORT        ?= 5432
PGDATABASE    ?= $(PRG)
PGUSER        ?= ma
PGPASSWORD    ?= $(shell < /dev/urandom tr -dc A-Za-z0-9 | head -c14; echo)
PGAPPNAME     ?= $(PRG)

PKG := ./cmd
SERVER_PKG_BUILD := "${PKG}/server"
CLIENT_PKG_BUILD := "${PKG}/client"

# -----------------------------------------------------------------------------
# docker part
APP_IMAGE  ?= $(PRG)

# image prefix
PROJECT_NAME ?= $(PRG)

# docker-compose image
DC_VER ?= 1.23.2
# -----------------------------------------------------------------------------
# dcape part
# dcape containers name prefix
DCAPE_PROJECT_NAME ?= dcape
# dcape postgresql container name
DCAPE_DB           ?= $(DCAPE_PROJECT_NAME)_db_1


define CONFIG_DEFAULT
# ------------------------------------------------------------------------------
# application config file, generated by make $(CFG)

# App/Docker listen addr
APP_LISTEN=$(APP_LISTEN)

# Docker image tag
APP_IMAGE=$(APP_IMAGE)

# Database

# Host
PGHOST=$(PGHOST)
# Port
PGPORT=$(PGPORT)
# Name
PGDATABASE=$(PGDATABASE)
# User
PGUSER=$(PGUSER)
# Password
PGPASSWORD=$(PGPASSWORD)
# App name
PGAPPNAME=$(PGAPPNAME)

endef
export CONFIG_DEFAULT

# ------------------------------------------------------------------------------

-include $(CFG)
export

.PHONY: all api build_server build_client

all: build_server build_client

api: ## Auto-generate grpc go sources
	go generate ./...

dep: ## Get the dependencies
	@go get -v -d ./...

build_server: dep api ## Build the binary file for server
	@go build -i -v -o $(SERVER_OUT) $(SERVER_PKG_BUILD)

build_client: dep api ## Build the binary file for client
	@go build -i -v -o $(CLIENT_OUT) $(CLIENT_PKG_BUILD)

run: build_server
	./$(SERVER_OUT) --debug --db.addr=localhost:15432 --addr=0.0.0.0:7071 \
	--db.name=${PGDATABASE} --db.user=${PGUSER} --db.password=${PGPASSWORD}

lint: ## run linter
	@golangci-lint run ./...

test: ## run grpc client tests
	APP_ADDR=localhost:7070 \
	go test -v -count=1 .

test1: ## run grpc client tests, port 7071
	APP_ADDR=localhost:7071 \
	go test -v -count=1 .


#	APP_ADDR=vivo:${APP_LISTEN} go test -v -count=1 .

# ------------------------------------------------------------------------------
# Docker

## старт контейнеров
up:
up: CMD=up -d
up: dc

## остановка и удаление всех контейнеров
down:
down: CMD=rm -f -s
down: dc

# $$PWD используется для того, чтобы текущий каталог был доступен в контейнере по тому же пути
# и относительные тома новых контейнеров могли его использовать
## run docker-compose
dc: docker-compose.yml
	@docker run --rm  \
	  -v /var/run/docker.sock:/var/run/docker.sock \
	  -v $$PWD:$$PWD \
	  -w $$PWD \
	  docker/compose:$(DC_VER) \
	  -p $$PROJECT_NAME \
	  $(CMD)

# ------------------------------------------------------------------------------
# DB operations (with docker and dcape)

# Wait for postgresql container start
docker-wait:
	@echo -n "Checking PG is ready..."
	@until [[ `docker inspect -f "{{.State.Health.Status}}" $$DCAPE_DB` == healthy ]] ; do sleep 1 ; echo -n "." ; done
	@echo "Ok"

# create user, db and load dump
db-create: docker-wait
	@echo "*** $@ ***" ; \
	docker exec -i $$DCAPE_DB psql -U postgres -c "CREATE USER \"$$PGUSER\" WITH PASSWORD '$$PGPASSWORD';" || true ; \
	docker exec -i $$DCAPE_DB psql -U postgres -c "CREATE DATABASE \"$$PGDATABASE\" OWNER \"$$PGUSER\";" || db_exists=1 ; \
	if [[ ! "$$db_exists" ]] ; then \
	    cat companyserv.sql | docker exec -i $$DCAPE_DB psql -U postgres -d $$PGDATABASE -1 -X ; \
	    echo "Restore completed" ; \
	fi

## drop database and user
db-drop: docker-wait
	@echo "*** $@ ***"
	@docker exec -it $$DCAPE_DB psql -U postgres -c "DROP DATABASE \"$$PGDATABASE\";" || true
	@docker exec -it $$DCAPE_DB psql -U postgres -c "DROP USER \"$$PGUSER\";" || true

psql: docker-wait
	@docker exec -it $$DCAPE_DB psql -U $$PGUSER -d $$PGDATABASE

psql1:
	@docker exec -it $${PRG}_db_1 psql -U $$PGUSER -d $$PGDATABASE

psql-local: docker-wait
	@psql -d "postgres://$$PGUSER:$$PGPASSWORD@/$$PGDATABASE?sslmode=disable"

# ------------------------------------------------------------------------------

## create initial config
$(CFG):
	@[ -f $@ ] || { echo "$$CONFIG_DEFAULT" > $@ ; echo "Warning: Created default $@" ; }

clean: ## Remove previous builds
	@rm $(SERVER_OUT) $(CLIENT_OUT)

help: ## Display this help screen
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
